/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.ebuildy.metry;

import com.github.ebuildy.metry.connectors.HTTPConnector;
import com.github.ebuildy.metry.connectors.SimpleTCPConnector;
import org.junit.Test;

import java.io.IOException;
import java.util.Properties;

import static org.junit.Assert.*;

public class MetrySinkTest {

    @Test public void selectGoodConnector() throws IOException {
        Properties p = new Properties();

        p.put(MetrySink.KEY_URL, "http://localhost");

        assertTrue(MetrySink.getConnector(p) instanceof HTTPConnector);

        p.put(MetrySink.KEY_URL, "tcp://localhost:8080");

        assertTrue(MetrySink.getConnector(p) instanceof SimpleTCPConnector);
    }


}
